[package]
authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]
categories = ["embedded", "no-std", "hardware-support"]
repository = "https://github.com/kjetilkjeka/s32k144evb.rs"
description = "Board support crate for s32k144evb"
keywords = ["arm", "cortex-m", "s32k144", "template"]
license = "MIT OR Apache-2.0"
name = "s32k144evb"
version = "0.3.0"

[dependencies]
cortex-m = "0.3.1"
cortex-m-rt = "0.3.5"
s32k144 = "0.5.0"
bit_field = "0.8.0"

[dev-dependencies.s32k144evb]
path = "."
features = ["panic-over-itm"]

[profile.dev]
opt-level = 0
debug = true
lto = true

[profile.release]
debug = true
lto = true

[features]
panic-over-itm = []
abort-on-panic = ["cortex-m-rt/abort-on-panic"]
