[package]
authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]
categories = ["embedded", "no-std"]
repository = "https://github.com/kjetilkjeka/s32k144evb.rs"
description = "Board support crate for s32k144evb"
keywords = ["arm", "cortex-m", "s32k144", "template"]
license = "MIT OR Apache-2.0"
name = "s32k144evb"
version = "0.1.0"

[dependencies]
cortex-m = "0.3.0"
s32k144 = "0.4.0"
bit_field = "0.7.0"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.2"

[profile.dev]
opt-level = 0
debug = true
lto = true

[profile.release]
debug = true
lto = true
