[package]
authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]
categories = ["embedded", "no-std", "hardware-support"]
repository = "https://github.com/kjetilkjeka/s32k144evb.rs"
description = "Board support crate for s32k144evb"
keywords = ["arm", "cortex-m", "s32k144", "template"]
license = "MIT OR Apache-2.0"
name = "s32k144evb"
version = "0.4.0"

[dependencies]
cortex-m = "0.3.1"
s32k144 = "0.6.0"
bit_field = "0.8.0"
embedded_types = "0.1.4"

[dependencies.cortex-m-rt]
version = "0.3.6"
default-features = false

[profile.dev]
opt-level = 0
debug = true
lto = true

[profile.release]
debug = true
lto = true

[features]
default = ["print-over-serial", "panic-over-serial"]
itm = []
panic-over-itm = ["itm"]
abort-on-panic = ["cortex-m-rt/abort-on-panic"]
serial = []
print-over-serial = ["serial"]
panic-over-serial = ["serial"]