[package]
authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]
categories = ["embedded", "no-std"]
description = "Board support crate for s32k144evb"
keywords = ["arm", "cortex-m", "s32k144", "template"]
license = "MIT OR Apache-2.0"
name = "s32k144evb"
version = "0.1.0"

[dependencies]
cortex-m = "0.2.10"
s32k144 = "0.2.0"
cortex-m-rt = "0.2.4"

[profile.dev]
opt-level = 0
debug = true
lto = true

[profile.release]
debug = true
lto = true
